### PR TITLE
Feature request: disposal of a single model

### LINKED ISSUE #147: Feature request: disposal of a single model
In my application I want to show only one model at a time. As soon as the user selects a different model, the old model should be disposed of so that the memory it occupys is cleared, while the scene and all other objects remain. I need a method that handles the disposal of the model for me, something like IfcManager.remove(model).

### PR DESCRIPTION
**Pull request by D4ve-R**
Update ifc-manager.ts:

Add `removeIfcModel(modelID: number)`, to support removing & disposing of single `IFCModel`s by modelID.

resolves #147

### CODE REVIEW

**Comment by D4ve-R** [comment]
Jest CI tests fail, see #181

**Comment by D4ve-R** [comment]
to work properly ifcjs/web-ifc-three#144 should be merged, to avoid memory leaking by `loader.ifcManager.close`.

**Comment by aka-blackboots** [comment]
When I remove the Ifc Model using `removeIfcModel(0)`, the shadow for the model is still visible in the Viewer.

**Comment by agviegas** [comment]
Yeah, probably the shadow will need to be removed when the model is removed 🤔

**Comment by D4ve-R** [comment]
I had to move the shadowdropper component to the ifcmanager, to make this work.  
But i feel like it doesn't belong there.
To put it in context component would make more sense.

**Comment by aka-blackboots** [comment]
@D4ve-R Does your previous commit remove the Shadow? I'm still seeing it.

**Comment by D4ve-R** [comment]
finally done, i also added the key event D to the example, for easy testing, it deletes models with ID 0

**Pull request merged**
