### PR TITLE
Processing IFC models that do not contain IFCBuilding

### LINKED ISSUE #161: Processing IFC models that do not contain IFCBuilding
### Description

When I try to get all the properties of an IFC model that does not contain IFCBuilding, an error occurs:

IFC models of strict structure are successfully processed.

A problem appears when exporting a model as a GLTF object. The model loads and displays successfully on the canvas, but the above error occurs when exporting, namely when retrieving properties:
`await ifcViewer.current.IFC.properties.serializeAllProperties(
      model
);`

### Expected Behavior

**serializeAllProperties** method successfully returns the result regardless of the presence that the IFC-model structure is strict.

### Steps to Reproduce

- **loadIfcUrl** [https://cdn.discordapp.com/attachments/912752967537537075/1025414451165413386/060_3.ifc](url)
- **serializeAllProperties** of loaded IFC model

### Environment

- "three": "0.135.0"
- "web-ifc-three": "0.0.115"
- "web-ifc-viewer": "1.0.176"

### LINKED ISSUE #168: serializeAllProperties returns lines in a different structure than getLine from ifcApi
Retrieving all the lines as a properties blob is great, however the lines that are retrieved do not have the same structure as the ones that you get from the `getLine` function. Digging into `IFCWorker.js:88765` the cause is very clear:

```
getItemProperty(modelID, id, properties) {
        try {
            const props = await this.webIfc.GetLine(modelID, id);
            if (props.type) {
                props.type = IfcTypesMap[props.type]; // ******** Q: Why is the type replaced from the number to the string?
            }
            this.formatItemProperties(props);
            properties[id] = props;
        }
        catch (e) {
            console.log(`There was a problem getting the properties of the item with ID ${id}`);
        }
    }
    formatItemProperties(props) {
        Object.keys(props).forEach((key) => {
            const value = props[key];
            if (value && value.value !== undefined)
                props[key] = value.value; // ************** Q: Why do you set it directly to the value and drop the object structure underneath
            else if (Array.isArray(value))
                props[key] = value.map((item) => {
                    if (item && item.value)
                        return item.value; // ************** Q: Same Question as above
                    return item;
                });
        });
    }
```

2 Questions:
- Why does the structure even change, i dont think there is a reason for it since it makes writing lines back to the ifc a lot harder (or basically impossible seeing how many different lines there are)
- Would it be possible to AT LEAST offer a function that does not do this?

### PR DESCRIPTION
**Pull request by D4ve-R**
Update ifc-properties.ts getBuilding():

Update `getBuilding` and  `getBuildingHeight`, to support serialization of models without IfcBuilding elements.  

If no IfcBuilding is in the model, `globalHeight` in `initializePropertiesObject`'s return value is set to 0.

resolves #161  

includes changes from #178, so resolves #168 too

### CODE REVIEW

**Comment by aka-blackboots** [comment]
@D4ve-R, Jest Tests are failing. Can you look into that?

**Comment by D4ve-R** [comment]
@aka-blackboots, yes they are failing, because there are no test files.
CI Tests fail with: `No tests found, exiting with code 1`.
Tbh, i have no idea how to solve this.

**Comment by D4ve-R** [comment]
If found the issue, there are no tests to run. I guess they got removed sometime in the past. 
I created an issue #181 and fixing pull request #182

**Comment by aka-blackboots** [comment]
Merging this PR for fixing issue #161, great work 🚀

**Comment by aka-blackboots** [comment]
This PR has merge conflicts because of the last merge, can you resolve them and commit them?

**Comment by D4ve-R** [comment]
sorry, i messed up there

**Comment by aka-blackboots** [comment]
Merging this PR for issue #161

**Pull request merged**
