### PR TITLE
Upgrade three.js deps to match web-ifc-three

### PR DESCRIPTION
**Pull request by pablo-mayrgundter**

### CODE REVIEW

**Comment by pablo-mayrgundter** [comment]
Addressed #188

**Comment by pablo-mayrgundter** [comment]
Per discussion, waiting to hear back about upgrades to web-ifc-three from @agviegas.

However, I think this PR is independent of that.

**Comment by iffies** [comment]
Curious how this issue resolves. I assumed that this repository wasn't updated to a more recent version of Three.js because it needed more changes than just the dependency version. And with the shift towards Open BIM Components, perhaps this is actually a legacy code base. Even if it's still the official way to get a jump start on making a BIM application, perhaps there were lessons learnt and those lessons are being applied to developments in other repositories that are the project's future.

**Comment by agviegas** [comment]
Hi, I am updating all the dependencies right now! Thanks for the PR, although I might push this to the latest version of three.

**Comment by agviegas** [comment]
@iffies the plan is to make everything a component, wich means:
- Making web-ifc-three have a component structure, so it's just another self-contained
- Making web-ifc-viewer import all generic tools from components, and leave it as an example project using web-ifc-three and components.

**Comment by agviegas** [comment]
Hi, I am reverting this change. I have tried building the project and there are many errors that will need to be addressed. Because now all the tools are going to be in ifcjs/components, and this repository will have a big refactor soon (to extract all the tools), I don't think it's worth spending time fixing all the issues that come up with the update.

**Comment by pablo-mayrgundter** [comment]
Hmm, sorry to hear it.  Yeah, it was unclear how to evaluate it.  It's hard to make PRs without a hermetic build process documented or in the scripts.

I was talking with @aka-blackboots about this and do suggest that be a priority going forward.

**Pull request merged**
