### PR TITLE
Add 2D dimension

### PR DESCRIPTION
**Pull request by mikhailmtion**
I have added the ability to take measurements in 2D. Toggler added, you can use it to switch to 2D measurement mode and get measurements at the top point.

Attached a screenshot
example (2)

### CODE REVIEW

**Comment by mikhailmtion** [comment]
@aka-blackboots , Hi, for some reason, the Eslint check does not pass. In the main branch, the same problem

**Comment by agviegas** [comment]
Hi, all our efforts are now going towards [this library](https://github.com/IFCjs/components), which will likely substitute both web-ifc-viewer and web-ifc-three. You can check the dimensions there, and feel free to open a PR if you think they need improvement!

**Comment by mikhailmtion** [comment]
@agviegas  Hi! How is it better than web-ifc-viewer?

**Comment by agviegas** [comment]
Some of the reasons are:
- It's more modular & flexible
- It's much faster to load models
- It consumes way less memory
- Has better postprocessing
- It has way more tools (and all new tools are going to be here)
- It's going to be maintained in the long term
- The whole documentation + tutorials + testing is going to be release by the end of the summer

**Pull request closed without merging**
